-- Create new DBT project from Git repo
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE DEMO_DB;

-- Create new dbt project from Git
CREATE OR REPLACE DBT PROJECT DBT_DEV.DATAVAULT_MULTI
    FROM '@GIT_REPOS.DATAVAULT_REPO/branches/main';

-- Run dbt
EXECUTE DBT PROJECT DBT_DEV.DATAVAULT_MULTI ARGS='run';
