USE DATABASE DEMO_DB;
USE SCHEMA DBT_DEV_RAW_VAULT;

CREATE OR REPLACE DYNAMIC TABLE SAT_CUSTOMERS_DETAILS
    TARGET_LAG = '1 day'
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    HK_H_CUSTOMERS,
    HASHDIFF,
    FIRST_NAME,
    LAST_NAME,
    CUSTOMER_EMAIL,
    CITY,
    COUNTRY,
    CREATED_DATE,
    CURRENT_TIMESTAMP() AS EFFECTIVE_TS,
    CURRENT_TIMESTAMP() AS DWH_VALID_TS,
    'DEMO_DB.DBT_DEV.RAW_CUSTOMERS' AS DSS_RECORD_SOURCE
FROM (
    SELECT
        MD5(COALESCE(CAST(CUSTOMER_ID AS VARCHAR), '')) AS HK_H_CUSTOMERS,
        MD5(
            COALESCE(CAST(FIRST_NAME AS VARCHAR), '') || '|' ||
            COALESCE(CAST(LAST_NAME AS VARCHAR), '') || '|' ||
            COALESCE(CAST(CUSTOMER_EMAIL AS VARCHAR), '') || '|' ||
            COALESCE(CAST(CITY AS VARCHAR), '') || '|' ||
            COALESCE(CAST(COUNTRY AS VARCHAR), '') || '|' ||
            COALESCE(CAST(CREATED_DATE AS VARCHAR), '')
        ) AS HASHDIFF,
        FIRST_NAME,
        LAST_NAME,
        CUSTOMER_EMAIL,
        CITY,
        COUNTRY,
        CREATED_DATE
    FROM DEMO_DB.DBT_DEV.RAW_CUSTOMERS
    WHERE CUSTOMER_ID IS NOT NULL
)
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY HK_H_CUSTOMERS, HASHDIFF
    ORDER BY CREATED_DATE
) = 1;

-- Verify
SELECT 'SAT_CUSTOMERS_DETAILS created' AS status, COUNT(*) AS row_count
FROM SAT_CUSTOMERS_DETAILS;

-- Show all Dynamic Tables
SELECT 'HUB_CUSTOMERS' AS table_name, COUNT(*) AS rows FROM HUB_CUSTOMERS
UNION ALL
SELECT 'SAT_CUSTOMERS_DETAILS', COUNT(*) FROM SAT_CUSTOMERS_DETAILS;

SHOW DYNAMIC TABLES IN SCHEMA DBT_DEV_RAW_VAULT;
