USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE DEMO_DB;

-- Fetch latest from Git
ALTER GIT REPOSITORY GIT_REPOS.DATAVAULT_REPO FETCH;

-- Create dbt project
CREATE OR REPLACE DBT PROJECT DBT_DEV.DATAVAULT_MULTI
    FROM '@GIT_REPOS.DATAVAULT_REPO/branches/main';

-- Run dbt
EXECUTE DBT PROJECT DBT_DEV.DATAVAULT_MULTI ARGS='run';
