-- Run dbt tests
USE ROLE ACCOUNTADMIN;
USE DATABASE DEMO_DB;
USE SCHEMA DBT_DEV;
USE WAREHOUSE COMPUTE_WH;

-- Execute dbt test
EXECUTE DBT PROJECT DEMO_DB.DBT_DEV.DATAVAULT_CUSTOMERS ARGS='test';
