-- Verify Data Vault Tables

-- Hub: Customers
SELECT 'HUB_CUSTOMERS' AS TABLE_NAME;
SELECT HK_H_CUSTOMERS, CUSTOMER_ID, DSS_RECORD_SOURCE
FROM DEMO_DB.DBT_DEV_RAW_VAULT.HUB_CUSTOMERS;

-- Satellite: Customer Details
SELECT 'SAT_CUSTOMERS_DETAILS' AS TABLE_NAME;
SELECT HK_H_CUSTOMERS, HASHDIFF, FIRST_NAME, LAST_NAME, CUSTOMER_EMAIL, CITY, COUNTRY
FROM DEMO_DB.DBT_DEV_RAW_VAULT.SAT_CUSTOMERS_DETAILS;

-- Summary
SELECT 'SUMMARY' AS REPORT;
SELECT 'HUB_CUSTOMERS' AS table_name, COUNT(*) AS rows FROM DEMO_DB.DBT_DEV_RAW_VAULT.HUB_CUSTOMERS
UNION ALL
SELECT 'SAT_CUSTOMERS_DETAILS', COUNT(*) FROM DEMO_DB.DBT_DEV_RAW_VAULT.SAT_CUSTOMERS_DETAILS;
